#!/bin/bash

exec 2>&1

{{#if bind.database.first.cfg.local_only ~}}
MYSQL_IP=127.0.0.1
{{else ~}}
MYSQL_IP={{bind.database.first.sys.ip}}
{{/if ~}}

############# Connect to Database #############################
mysql_ready() {
    mysqladmin ping -h $MYSQL_IP -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} > /dev/null 2>&1
}

if !(mysql_ready) then
     echo "waiting for mysql ..."
     exit 1
fi

mysql -h $MYSQL_IP -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} -e "create database IF NOT EXISTS {{cfg.database_name}}"
